### PR TITLE
firebase libraries in jar 9.4.0

### PR DESCRIPTION
**Pull request by darknos**

### CODE REVIEW

**Comment by chrisribe** [comment]
Thanks darknos

**Comment by darknos** [comment]
I extracted them myself but I found probably better way:
https://github.com/dandar3/android-google-firebase-README

**Comment by darknos** [comment]
Thank you for great job re iOS module. 
Are you going to continue work on Android module?

**Comment by chrisribe** [comment]
I will need to in the future... No timeline though.

I put firebase on hold until they fixed the in-app purchase events counts.
This would cause false purchase events like 40x real events.
https://firebase.google.com/support/release-notes/ios

Funny how they call it a "feature"

> Added a feature to validate the authenticity of in-app purchase events before they are reported by Firebase Analytics.

Will need to update the SDK libraries...

**Comment by chrisribe** [comment]
Hi  @darknos,

I have started looking into implementing the android part of the firebase appcelerator module.
Coming from an iOS world the learning curve is quite steep.... You seem to know a thing or two or 2000 ;)

Could you detail how you extracted the jar's I looked up the repo from Dandar3 but I am kinda lost.
https://github.com/dandar3/android-google-firebase-README

And what is this script import-google-services.js do exactly...

I think it's used to translate the json file is to produce two XML files which you can reference as Android resources in your Java code. [(as mentioned here )](https://developers.google.com/android/guides/google-services-plugin). So OMG there are so many moving parts...

I started trying to implement the official getting started guide... Had tons of SDK updates to get 1st 
[https://firebase.google.com/docs/android/setup](https://firebase.google.com/docs/android/setup)

Finally got the [firebase quickstart](https://github.com/firebase/quickstart-android) to run but... wow

Any feedback would be great thanks.
Chris

**Comment by darknos** [comment]
The first I need to say that I stopped working with Firebase on android due to dexer limitation to 64K and no multi-dex in Titanium SDK 5.x. I already have more then 50k classes in my libraries in OpenGL games so if I try to compile Firebase libraries too I get dexer error "trouble writing output: Too many method references: 69321; max is 65536."

You are right re import-google-services.js. it do the same as gradle script in Android Studio - it prepares two XML based on google-services.json that specific to your project. You'll need these files in a project which will use ti.firebase module. there are details about your Firebase project.

**Comment by chrisribe** [comment]
Thanks for the info, will keep grinding on this today...

Nice you are running opengl games under Titanium ? 
Any links, title names or libraries would you suggest... Just curious, always thought titanum to slow to run games ;)

Chris

**Comment by darknos** [comment]
I have an engine forked form the same source as Platino (http://platino.io) but with additional features and box-2d integrated.

I'm going to make it open source but have no time to clean up/comment sources, write docs, before publishing.

my store accounts:
https://itunes.apple.com/developer/ipublisher-ua/id468043785
https://play.google.com/store/apps/developer?id=iPublisher+UA

I'd recommend to play this:
https://itunes.apple.com/us/app/run-rabbit-run-maze-puzzle/id925383186?mt=8

**Comment by chrisribe** [comment]
Nice I like the run rabit run app...
Good job :)

**Pull request merged**
